### ISSUE TITLE
Code for extracting time series with data driven atlases

### ISSUE THREAD

**Issue by Shotgunosine** [KamalakerDadi/benchmark_rsfMRI_prediction#1]
This is a fantastic repository and the associated paper is a great resource. Thank you so much for sharing. I may have missed it in the scripts provided, but could you share the code you used to extract time series and train classifiers for the data driven atlases? If that code isn't readily available, an example including dictionary learning would be great since that is the method recommended in the paper.

**Comment by KamalakerDadi** [comment]
Hi @Shotgunosine 
Thanks a lot for your interest.

This repo starts with pre-extracted timeseries even for data-driven atlases. You are asking if I can provide scripts which I used to extract these timeseries ?
You need them for all datasets ? At the moment, I can push scripts I used to extract timeseries. Is that fine or you need complete pipeline script ?

**Comment by Shotgunosine** [comment]
I was just looking for an example of how fit the data driven atlases and how extract time series for them. I thought it might be in part of the classifier training since if I recall correctly, the data driven atlases are fit on the training data only.

**Comment by KamalakerDadi** [comment]
>thought it might be in part of the classifier training since if I recall correctly, the data driven atlases are fit on the training data only.

yes, thats exactly it. sorry for being so late.

How do you want to see the example ?

**Comment by Shotgunosine** [comment]
It could just be another .py file to run the training on the data driven atlases, or maybe I'm not understanding what you're asking.

**Comment by KamalakerDadi** [comment]
Sorry, I lost this. But, the script I used is here. It requires other supporting Python files. But, it would give you an idea. Here it is https://gist.github.com/KamalakerDadi/3530c4430eacd976f18193e1fd5a6eea
