### ISSUE TITLE
how to get the structural data,such as T1 data for MRI?

### ISSUE THREAD

**Issue by mutual-ai** [KamalakerDadi/benchmark_rsfMRI_prediction#2]
is it possible to combine sMRI and fMRI for improving the prediction?

**Comment by mutual-ai** [comment]
how to get the sMRI of all subjects?

**Comment by KamalakerDadi** [comment]
Hey,
Both sMRI and fMRI, will be part of your data download request. So, you should be filing your own request to download them.
